name: Manual workflow

on:
  push:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: create file
        run: echo $(date -Is) > $(date -Is).txt
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.0
